/**
 * Base class for errors thrown by {@link MarkdownSourceMap} lookups.
 *
 * Extends `RangeError` so existing `catch (RangeError)` handling keeps
 * working, and adds a stable {@link SourceMapError.code} so downstream
 * consumers can pick a recovery strategy even when `instanceof` is
 * unreliable — e.g. dual CJS/ESM package instances, duplicate installs, or
 * errors crossing a worker / serialization boundary:
 *
 * ```ts
 * if (
 *   error instanceof SourceMapConsistencyError
 *   || (error instanceof Error
 *     && (error as { code?: string }).code === 'ERR_SOURCE_MAP_CONSISTENCY')
 * ) {
 *   // recovery strategy
 * }
 * ```
 *
 * @public
 */
export class SourceMapError extends RangeError {
  /** Stable machine-readable error code. */
  readonly code: string;

  constructor(code: string, message: string) {
    super(message);
    this.name = new.target.name;
    this.code = code;
  }
}

/**
 * Thrown when a mapped node has been modified since parsing. The recorded
 * mapping only describes the original parsed value, so any answer would be
 * fabricated.
 *
 * Stable `code`: `ERR_SOURCE_MAP_CONSISTENCY`.
 *
 * @public
 */
export class SourceMapConsistencyError extends SourceMapError {
  constructor(message = 'The mapped node has changed since parsing') {
    super('ERR_SOURCE_MAP_CONSISTENCY', message);
  }
}

/**
 * Thrown when no source mapping is available for the given node: the node
 * belongs to another document, was generated by a plugin or added after
 * parsing, has no supported source mapping, or has no source position at
 * all. The exact reason is described in the error message.
 *
 * Stable `code`: `ERR_SOURCE_MAP_UNAVAILABLE`.
 *
 * @public
 */
export class SourceMapUnavailableError extends SourceMapError {
  constructor(message = 'No source mapping is available for this node') {
    super('ERR_SOURCE_MAP_UNAVAILABLE', message);
  }
}
