/**
 * Stable machine-readable codes carried by {@link SourceMapError} variants.
 *
 * @public
 */
export type SourceMapErrorCode =
  | 'ERR_SOURCE_MAP_CONSISTENCY'
  | 'ERR_SOURCE_MAP_UNAVAILABLE';

/**
 * Base class for errors thrown by {@link MarkdownSourceMap} lookups.
 *
 * Extends `RangeError` so existing `catch (RangeError)` handling keeps
 * working, and adds a stable `code` so downstream consumers can pick a
 * recovery strategy even when `instanceof` is unreliable — e.g. dual
 * CJS/ESM package instances or duplicate installs. The error `name` is set
 * explicitly per class rather than relied upon from `new.target`, so the
 * public names stay stable under any bundler minification.
 *
 * @public
 */
export class SourceMapError extends RangeError {
  /** Stable machine-readable error code. */
  readonly code: SourceMapErrorCode;

  constructor(code: SourceMapErrorCode, message: string) {
    super(message);
    this.name = 'SourceMapError';
    this.code = code;
  }
}

/**
 * Thrown when a mapped node has been modified since parsing. The recorded
 * mapping only describes the original parsed value, so any answer would be
 * fabricated.
 *
 * Stable `code`: `ERR_SOURCE_MAP_CONSISTENCY`.
 *
 * @public
 */
export class SourceMapConsistencyError extends SourceMapError {
  constructor(message = 'The mapped node has changed since parsing') {
    super('ERR_SOURCE_MAP_CONSISTENCY', message);
    this.name = 'SourceMapConsistencyError';
  }
}

/**
 * Thrown when no source mapping is available for the given node: the node
 * belongs to another document, was generated by a plugin or added after
 * parsing, has no supported source mapping, or has no source position at
 * all. The exact reason is described in the error message.
 *
 * Stable `code`: `ERR_SOURCE_MAP_UNAVAILABLE`.
 *
 * @public
 */
export class SourceMapUnavailableError extends SourceMapError {
  constructor(message = 'No source mapping is available for this node') {
    super('ERR_SOURCE_MAP_UNAVAILABLE', message);
    this.name = 'SourceMapUnavailableError';
  }
}
