import type {
  MarkdownCodeNode,
  MarkdownDefinitionNode,
  MarkdownInlineCodeNode,
  MarkdownLinkNode,
  MarkdownNode,
  MarkdownTextNode,
  ParsedPosition,
} from '../types';

/**
 * The kind of transformation the parser applied to turn a slice of the raw
 * Markdown source into the corresponding slice of a node's normalized value.
 *
 * @internal
 */
export type SourceMapSegmentKind =
  | 'literal'
  | 'escape'
  | 'character-reference'
  | 'normalization';

/**
 * A single contiguous mapping between a half-open range of a node's
 * normalized `value` (UTF-16 code unit indices) and the corresponding
 * half-open range of the raw Markdown source (absolute offsets).
 *
 * Adjacent segments never overlap and never leave gaps across the whole
 * `node.value`.
 *
 * @internal
 */
export interface MarkdownSourceMapSegment {
  /** Half-open interval within `node.value` (JavaScript string indices). */
  valueStart: number
  /** Half-open interval within `node.value` (JavaScript string indices). */
  valueEnd: number

  /** Absolute half-open interval within the raw Markdown source. */
  sourceStart: number
  /** Absolute half-open interval within the raw Markdown source. */
  sourceEnd: number

  /**
   * What the parser did to this slice.
   *
   * - `literal`: copied verbatim from source.
   * - `escape`: a CommonMark backslash escape (`\(` → `(`).
   * - `character-reference`: a named/decimal/hex character reference
   *   (`&amp;` → `&`); source and value lengths may differ.
   * - `normalization`: the parser replaced an illegal code point with the
   *   Unicode replacement character (U+FFFD), or otherwise normalized the
   *   slice without decoding an entity.
   */
  kind: SourceMapSegmentKind
}

/**
 * Sidecar source map produced alongside a parse. Maps supported value nodes to
 * compressed segments that reconstruct supported normalized fields from the
 * raw Markdown source.
 *
 * @public
 */
export interface MarkdownSourceMap {
  /**
   * Returns the raw Markdown substring that produced the given node's
   * normalized value.
   *
   * Only accepts a node that belongs to the tree returned by the same
   * `parseMdWithSourceMap()` call and that had a real source span at parse
   * time. The returned source reflects what produced the node when it was
   * parsed: source offsets are snapshotted at parse time, so mutating
   * `node.position` afterwards does not change the result.
   *
   * Failure modes:
   *
   * - {@link SourceMapUnavailableError} — the node belongs to another
   *   document, or had no source position at parse time (e.g. it was
   *   generated by a plugin or added after parsing). No mapping is fabricated.
 * - {@link SourceMapConsistencyError} — a mapped `value` or `url` field has
 *   been modified since parsing; the map only covers the original field value.
 *   (Only mapped fields are subject to this check; `position` mutation never
 *   triggers it because offsets are read from the parse-time snapshot.)
   *
   * @param node - A node from the document this map was built for.
   * @returns The raw Markdown that produced `node`.
   */
  getRaw(
    node: MarkdownNode | MarkdownTextNode | MarkdownInlineCodeNode | MarkdownCodeNode
    | MarkdownLinkNode | MarkdownDefinitionNode,
  ): string

  /**
   * Maps a half-open range of a supported node's normalized `value` back to
   * the corresponding range in the raw Markdown source. Supported nodes are
   * `text`, `inlineCode`, and block `code`.
   *
   * The returned range is monotonically increasing and covers the union of
   * every source segment spanned by `[valueStart, valueEnd)`.
   *
   * Failure modes:
   *
   * - {@link SourceMapUnavailableError} — the node belongs to another
   *   document, was generated or added after parsing, or is not a
   *   supported `text`, `inlineCode`, or `code` node. No mapping is fabricated.
   * - {@link SourceMapConsistencyError} — the mapped node has been modified since
   *   parsing; the map only covers the original parsed value.
   * - `RangeError` — `valueStart` / `valueEnd` are not finite integers, are
   *   out of bounds, are reversed, or (for an empty range) fall inside an
   *   atomic construct where no accurate source boundary exists.
   *
   * @param node - A supported value node from the document this map was built for.
   * @param valueStart - Start index into `node.value` (inclusive).
   * @param valueEnd - End index into `node.value` (exclusive).
   * @returns The source range covering the requested value slice.
   */
  getSourceRange(
    node: MarkdownTextNode | MarkdownInlineCodeNode | MarkdownCodeNode,
    valueStart: number,
    valueEnd: number,
  ): ParsedPosition

  /**
   * Maps a half-open range of a named normalized field back to the raw
   * Markdown source. The current field is `url`, supported by `link` and
   * `definition` nodes. URL escapes and character references are atomic: a
   * range intersecting one returns that construct's complete source span.
   *
   * Failure modes match `getSourceRange()`; modifying the mapped `url` field
   * throws {@link SourceMapConsistencyError}.
   */
  getFieldSourceRange(
    node: MarkdownLinkNode | MarkdownDefinitionNode,
    field: 'url',
    valueStart: number,
    valueEnd: number,
  ): ParsedPosition
}

/**
 * Result of {@link parseMdWithSourceMap}.
 *
 * @public
 */
export interface ParsedMarkdownDocument {
  /** The fully positioned AST, identical to what {@link parseMd} returns. */
  ast: import('../types').PositionedMarkdownRoot
  /** Sidecar source map for resolving supported value ranges to raw source. */
  sourceMap: MarkdownSourceMap
}
