name: build

on: [pull_request, push]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.3

      - name: Install modules and build projects
        run: pnpm install && pnpm run build

      - name: Run tests
        run: pnpm run test

  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.3

      - name: Install modules and build projects
        run: pnpm install && pnpm run build

      - name: Run tests
        run: pnpm run lint
